### ISSUE TITLE
Long-running WebSocket connection stops sending data

### ISSUE THREAD

**Issue by meteorpublish** [coinbase/coinbase-pro-node#104]
I have the following code listening for trade matches:

```js
webSocket.on('message', data => {
  if (data.type === 'match') {
    // Trade occurred
    console.log(`${data.side} ${data.size} ${data.product_id} @ ${data.price} @ ${data.time}`);
});
```

After a variable amount of time (typically a few hours), the socket stops receiving any messages. I have not seen any errors.

Any idea what might be going on? The setup is as followes:

```js
const Gdax = require('gdax');

const products = {
  'BTC-USD': { vol: 0 },
  'ETH-USD': { vol: 0 },
  'LTC-USD': { vol: 0 },
  'BTC-EUR': { vol: 0 },
  'ETH-EUR': { vol: 0 },
  'LTC-EUR': { vol: 0 },
  'BTC-GBP': { vol: 0 },
  'ETH-GBP': { vol: 0 },
  'ETH-BTC': { vol: 0 },
};
const webSocket = new Gdax.WebsocketClient(Object.keys(products));
```

**Comment by fb55** [comment]
We terminate the connection shortly after deploying the feed service.

**Comment by meteorpublish** [comment]
> (or rather: this library should handle that properly)

:+1: 

Until then, what would be the timeframe to reconnect after? Seconds? And what can be done about the missed messages during that timeframe?

**Comment by runia1** [comment]
@meteorpublish I also noticed this and have implemented the following logic to auto-reconnect:

```
// if it closes reconnect
websocket_client.on('close', (data) => {
    log_message('ERROR', 'Websocket Error', `websocket closed unexpectedly with data: ${data}. Attempting to re-connect.`);

    // try to re-connect the first time...
    websocket_client.connect();
    
    let count = 1;
    // attempt to re-connect every 30 seconds.
    // TODO: maybe use an exponential backoff instead
    const interval = setInterval(() => {
        if (!websocket_client.socket) {
            count++;
            
            // send me a email if it keeps failing every 30/2 = 15 minutes
            if (count % 30 === 0) {
                const time_since = 30 * count;
                log_message('CRIT', 'Websocket Error', `Attempting to re-connect for the ${count} time. It has been ${time_since} seconds since we lost connection.`);
            }
            websocket_client.connect();
        }
        else {
            clearInterval(interval);
        }
    }, 3000);
});
```

**Comment by SpaceMonkeyForever** [comment]
Hello, there

I know this is not the right place to ask this question, but it's the best I could find.

I have a problem when reconnecting, but I'm not using Node. However, I think you might still know the answer since it could be something on Coinbase side.

So, I'm using C# and when the websocket connection drops, I wait 10 seconds, dispose websocket, re-open connection and send the same subscription message again. For some reason, nothing happens.. I don't get back any messages. If I restart my application then it will work fine, so it's actually probably something on my side, but it is worth checking.

any ideas?

**Comment by rmm5t** [comment]
> So, I'm using C# and when the websocket connection drops, I wait 10 seconds, dispose websocket, re-open connection and send the same subscription message again. For some reason, nothing happens..

This sounds like you're forgetting to re-bind your event handlers to the new websocket instance.

> so it's actually probably something on my side, but it is worth checking.

Yes, this is definitely a client-side issue. I can connect, disconnect, reconnect, etc just fine against a Websocket within the same runtime.

**Comment by SpaceMonkeyForever** [comment]
You were right.. I forgot to rebind the event handler for MessageReceived. Funny thing is that I didn't forget to rebind the other events like Closed to retry connecting again. Thank you!

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
