### ISSUE TITLE
High CPU usage when reconnecting to the websocket

### ISSUE THREAD

**Issue by meteorpublish** [coinbase/coinbase-pro-node#106]
In order to solve #104, I'm creating a new WebsocketClient when there has been no data for 10+ seconds:

```js
let webSocket = new Gdax.WebsocketClient(Object.keys(products));
webSocket.on('message', handleData);

// Dump points to the database, and write to console the latest prices for contracts
setInterval(async function heartbeat() {
  if (points.length === 0) {
    console.warn('Stopped receiving data from the websocket. Recreating it...');
    webSocket = new Gdax.WebsocketClient(Object.keys(products));
    webSocket.on('message', handleData);
  }
  await dumpPoints(...);
}, 10000);
```

What happens now is that after running the script for a day or so, CPU utilization nears 100%:

![image](https://user-images.githubusercontent.com/10043369/30236990-95ce6450-94dc-11e7-83d3-8abd8e762c1c.png)

This isn't due to `dumpPoints()` or `handleData()` because that code is unchanged from the version before I filed #104. (On the other hand, the script would just not receive any data after a few hours to begin with, hence filing that issue).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
