### ISSUE TITLE
Ticker channel output does not match sample data shown in documentation

### ISSUE THREAD

**Issue by shannb** [coinbase/coinbase-pro-node#140]
So I am subscribing to the ticker channel with the following payload: 

```js
var info = {
    "type": "subscribe",
    "product_ids": [
        "ETH-USD",
        "ETH-EUR"
    ],
    "channels": [
        {
            "name": "ticker",
            "product_ids": [
                "ETH-BTC"
            ]
        },
    ]
}
```

I am getting the following data payload back:

```js
{ type: 'ticker',
sequence: 305122881,
product_id: 'LTC-BTC',
price: '0.00915000',
open_24h: '0.00913000',
volume_24h: '61559.04412384',
low_24h: '0.00903000',
high_24h: '0.00963000',
 volume_30d: '2306951.35609583',
best_bid: '0.00915',
 best_ask: '0.00916' }
```

This is inconsistent with the output for ticker channel that your documentation shows.   The documentation is currently showing the following output from a single record in this stream for ticket channel:

```js
{
    "type": "ticker",
    "trade_id": 20153558,
    "sequence": 3262786978,
    "time": "2017-09-02T17:05:49.250000Z",
    "product_id": "BTC-USD",
    "price": "4388.01000000",
    "side": "buy", // Taker side
    "last_size": "0.03000000",
    "best_bid": "4388",
    "best_ask": "4388.01"
}
```

We need to get the data shown by the documentation.  is there some other attributes or subscription message necessary to get the data shown in your docs for the ticker channel?

**Comment by rmm5t** [comment]
Tagging @a--hoang

**Comment by fb55** [comment]
For general context: The first event is returned immediately represents the current state. That's why a couple of fields are missing. They are present in all subsequent messages.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
