### ISSUE TITLE
cancelOrder has null callback data

### ISSUE THREAD

**Issue by Arombalski** [coinbase/coinbase-pro-node#156]
Is there something off with the cancelOrder function?  Doesn't seem right that the cancelOrder request from an authorized client returns a null message in its data.  Shouldn't there be something similar to an order submission or a full channel message?  Since GDAX doesn't let you getOrder on a cancelled order (the order ID is gone), there doesn't seem to be any options to see how much of the order was filled before it was cancelled (partial fill).

Here is some sample code.  data returns null.  Thanks for taking a look!

```js
const GDAX = require('gdax');
const key = 'powerfulapikey';
const b64secret = 'secret';
const passphrase = 'supersecretpass';
const sandboxURI = 'https://api-public.sandbox.gdax.com';
const authedClient = new GDAX.AuthenticatedClient(key, b64secret, passphrase, sandboxURI);

var orderId = '5b5ed158-5432-41f5-829d-7e83dea86d98';

authedClient.cancelOrder(orderId, function(err, response, data){
    if(err){
        console.log("Error cancelling an order:", err);
    }
    else{
        console.log('RESPONSE')
        console.log(response);
        console.log('DATA')
        console.log(data);                   
    }
});
```

**Comment by rmm5t** [comment]
The [GDAX API has no response](https://docs.gdax.com/#place-a-new-order), so I'd argue that the wrapper library should mimic this.

You should instead subscribe to the websocket feed and listen for the canceled order message of your particular order. It will come in immediately after you issue a successful `cancelOrder()`.  I think this is the only (correct) way to handle this without incurring any potential race conditions.

The feed message payload will look something like this:

```js
{
  type: 'done',
  side: 'buy',
  order_id: '00000000-1111-4444-2222-333333333333',
  reason: 'canceled',
  product_id: 'ETH-USD',
  price: '286.25000000',
  remaining_size: '0.23430000',
  sequence: 1463331000,
  user_id: '00000000-1111-4444-2222-333333333333',
  profile_id: '00000000-1111-4444-2222-333333333333',
  time: '2017-11-12T19:28:16.265000Z'
}
```

**Comment by fb55** [comment]
This is a bug in our API. The result is supposed to be the ID of the canceled order.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
