### ISSUE TITLE
Stop Limit order is not documented

### ISSUE THREAD

**Issue by rclai** [coinbase/coinbase-pro-node#164]
I have no idea where to report this but I noticed that the ordering documentation for stop orders does not include what the parameters should be when you want to do a stop _limit_ order. Right now it looks like you can only set a stop price but no limit price:

https://docs.gdax.com/#stop-order-parameters

If someone on the gdax team can just chime in here that would be greatly appreciated.

**Comment by fb55** [comment]
Agreed this should be documented. For now, please have a look at the requests the website is sending, as it is just another client for the API.

**Comment by rmm5t** [comment]
I was also curious about this, so I took @fb55's advice to inspect what the GDAX website does under the hood. Distilling it all down, the following worked for me. Basically, you submit a standard `limit` order, but with a couple extra properties defining the stop (note the `stop` and `stop_price` properties):

```js
authenticatedClient.sell( {
  type: "limit",
  product_id: "BTC-USD",
  size: "0.005",
  price: "10100",      // the limit price
  stop: "entry",       // currently undocumented
  stop_price: "10000", // currently undocumented
});
```

**Comment by rclai** [comment]
Ah, yes, I did that. I will leave this issue open until this is documented or unless a maintainer closes it.

**Comment by sfkiwi** [comment]
Has there been any progress on this? It looks like its possible to execute the stop limit by adding the `stop` and `stop_price` keys to the order object when you are using `gdax-node` directly, however this issue affects the Gdax Trading Toolkit also and there doesn't seem to be any easy way of overriding the typescript limit order declaration, so as of yet I haven't figured out a way of executing a stop limit order through the gdax-tt. The issue needs to be resolved in gdax-node first.

**Comment by sfkiwi** [comment]
Submitting PR to add the necessary fields to index.d.ts type declaration #286

**Comment by rmm5t** [comment]
Tagging @a--hoang

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
