### ISSUE TITLE
Add initialised event to OrderBookSync

### ISSUE THREAD

**Issue by axeldomingues** [coinbase/coinbase-pro-node#167]
The OrderbookSync example in the README

```
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
console.log(orderbookSync.books['ETH-USD'].state());

```
doesn't return anything. It just prints out

`{ asks: [], bids: [] }`

and that's it.

Not even after 5 seconds or any other period. Any help?

**Comment by rod-farva-sql** [comment]
Here is the sample code that worked for me.. see issue #144 

const Gdax = require('gdax');
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
setTimeout(function() { console.log(orderbookSync.books['ETH-USD'].state()); }, 5000);

If that doesn't work, try again at a different time as I've had it not work randomly.   I wish there was more documentation/examples on using orderbooksync.

**Comment by axeldomingues** [comment]
No it does not work for me. Still return empty order book :(

```
const Gdax = require('gdax');
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);

var waitTill = new Date(new Date().getTime() + 1 * 1000);
while(true){
    if(waitTill< new Date()){
        waitTill = new Date(new Date().getTime() + 1 * 1000);
        console.log(orderbookSync.books['ETH-USD'].state());
    }
}
```
Does the code above work for you? It does not for me either :(

**Comment by rod-farva-sql** [comment]
Hi,
I tried your code and it just keeps outputting the same lines..

{ asks: [], bids: [] }
{ asks: [], bids: [] }

**Comment by axeldomingues** [comment]
Yes it doesn't... No sure why... But i tried a big time (30s) for the code below and it did work.

```
const Gdax = require('gdax');
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
setTimeout(function() { console.log(orderbookSync.books['ETH-USD'].state()); }, 30000);
```

Thannk you @rod-farva-sql , will start from here and will try to understand why.

Would be nice that someone could help from the project.

Cheers.

**Comment by jontonsoup4** [comment]
@axeldomingues I ran across the same issue. It appears that the maintainers on this project haven't uploaded the github version to npm, and my assumption is that you have the version from npm downloaded. To fix this remove gdax with `npm uninstall gdax` and install the github version with `npm install coinbase/gdax-node` (or with yarn: `yarn add coinbase/gdax-node`)

**Comment by fb55** [comment]
The state is loaded lazily, that's why there isn't any information initially. There should definitely be some event that's fired once it is initialised.

**Comment by jrhea** [comment]
I do something like this:
```
var orderbookSync = new Gdax.OrderbookSync(products);
orderbookSync.on('message',data => {
  var book = orderbookSync.books['ETH-USD'].state();
  if(book.asks.length == 0 && book.asks.length == 0){
    //console.log("Waiting for data...");
  } 
  else {
    console.log(JSON.stringify(book));
  } 
});
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
