### ISSUE TITLE
WebsocketClient.disconnect() issue

### ISSUE THREAD

**Issue by macbeth8c** [coinbase/coinbase-pro-node#226]
Hello,
If one calls WebsocketClient.disconnect() method (which is not officially exposed in the interface, I know :), the disconnect or onClose methods invalidate the socket reference before other functions wish to use it, e.g. remaining data receive (the disconnect does not occur immediately). The error is thrown:

> Could not disconnect (not connected)
Or null pointer exceptions stating that socket is null already.

. I fixed it by commenting the following lines & added a different conditions.
```
  connect() {
    if (this.socket && this.socket.readyState === Websocket.OPEN) {
      this.socket.close();
    }

    this.socket = new Websocket(this.websocketURI);

    this.socket.on('message', this.onMessage.bind(this));
    this.socket.on('open', this.onOpen.bind(this));
    this.socket.on('close', this.onClose.bind(this));
    this.socket.on('error', this.onError.bind(this));
  }

  disconnect() {
    if (!this.socket || this.socket.readyState !== Websocket.OPEN) {
      throw new Error('Could not disconnect (not connected)');
    }
    this.socket.close();
    //this.socket = null;
  }
//...
  onClose() {
    //this.socket = null;
    this.emit('close');
  }
```
In my snippets you can see another way to check for connection status using ws.OPEN.

Cheers

**Comment by rmm5t** [comment]
> the disconnect or onClose methods invalidate the socket reference before other functions wish to use it, e.g. remaining data receive (the disconnect does not occur immediately).

Could you elaborate on this more? I cannot reproduce your issue. What other methods are trying to use the socket reference after `close` is emitted? For example, the only methods that reference `this.socket` while a socket is potentially open are `onClose()` and `disconnect()`.

For example, to test, I set an interval timer to call `disconnect()` every second while reading from the `full` channel, and I cannot trigger the same behavior that you're seeing. Btw, I run my websocket under a "Feed" wrapper that automatically reconnects whenever it recognizes that the underlying websocket was disconnected (via `close` event).

**Comment by macbeth8c** [comment]
Hi,
to reproduce the issue in the easiest way I use the following code
```
websocket.on('message', processTickerData);
websocket.on('error', err => { console.log(util.inspect(err, { showHidden: false, depth: null })) });
websocket.on('close', () => { console.log('Stream closed.') });
websocket.on('open', () => { console.log('Stream opened.') });


setInterval(function () {
  console.log('reopen attempt.')
  websocket.connect();
}, 2000);
```
```
TypeError: Cannot read property 'send' of null
    at WebsocketClient.onOpen (D:\Development\...\node_modules\gdax\lib\clients\websocket.js:70:17)
    at emitNone (events.js:106:13)
    at WebSocket.emit (events.js:208:7)
    at WebSocket.setSocket (D:\Development\...\node_modules\ws\lib\WebSocket.js:170:10)
    at ClientRequest._req.on (D:\Development\...\node_modules\ws\lib\WebSocket.js:709:10)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at TLSSocket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
```
since the connect also do disconnect, you will see the problem quickly.

Cheers

**Comment by rmm5t** [comment]
Calling `connect` on an already connected socket is a quite bizarre. I'd argue that calling connect on a connected socket should throw an Error itself. In other words, the behavior that you're simulating is flawed, but I think there's still an underlying bug in the code.

> since the connect also do disconnect

Well, this is the actual underlying problem. It cannot issue a close and reconnect in the same function (as you've pointed out).  Connect should not call `close()` if the socket is already open unless it's going to wait (properly) for a reconnect until after `close` event is both emitted and the underlying socket is finalized (which I don't think we have direct access to).

Before I offer other suggestions, **may I ask why you're calling `connect()` on an open socket repeatedly?**

**Comment by macbeth8c** [comment]
Hi,

> may I ask why you're calling connect() on an open socket repeatedly?

I wrote my snippet just to demonstrate the error in an easy way. I don't really have this construct in my production code. I just used it because connect() calls disconnect() very short time from each other.
The bottom line is, that the same error can happen if you subsequently call disconnect() and connect() from external code repeatedly.
So if you change the function to

```
setInterval(function () {
  console.log('reopen attempt.')
  websocket.disconnect();
  websocket.connect();
}, 2000);
```
The same will happen.

> I'd argue that calling connect on a connected socket should throw an Error itself.

I don't think you getting closer to the problem that I try to communicate here. **That it is improper to null the reference to a socket and then use this information to determine if the socket is open or not**. It is because socket.close() function is asynchronous and can take some time depends on many factors.

Kind regards
Piotr

**Comment by macbeth8c** [comment]
I have fixed both the null and calling connect() from disconnect() in my local branch. I can create a PR if you wish?

**Comment by rmm5t** [comment]
Thanks for the extra clarification. I understand your concerns better now. Thanks.

> ...That it is improper to null the reference to a socket and then use this information to determine if the socket is open or not. 

I agree that solely checking `null` for whether the underlying socket is open or not is the wrong way to go, but nulling the reference has no bearing on the socket. Nonetheless, I agree that nulling the reference is wasted, because it yields no value.

There are obviously a few issues compounding themselves with the connect/disconnect workflow.

>  I can create a PR if you wish?

Yes, PRs are always welcome.
