### ISSUE TITLE
Gdax.WebsocketClient not working

### ISSUE THREAD

**Issue by R-Pete-G** [coinbase/coinbase-pro-node#238]
Hi,

When I use the example in the README:
`const websocket = new Gdax.WebsocketClient(['BTC-USD', 'ETH-USD']);`

I get the following warnings:
`Attempt to set a forbidden header was denied: Sec-WebSocket-Version`
`Attempt to set a forbidden header was denied: Sec-WebSocket-Key`
`Attempt to set a forbidden header was denied: Sec-WebSocket-Extensions`
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ws-feed.gdax.com/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

And the error:
`Error: XHR error ClientRequest.prototype._onFinish/xhr.onerror`

If I try and use the websocket normally, with something like this:
`const websocket = new WebSocket('wss://ws-feed.gdax.com');`

It works fine.

Is the `Gdax.WebsocketClient` method supposed to work? Will I be unable to interact with it in certain ways if I don't use this method?

**Comment by rmm5t** [comment]
I don't think `gdax-node` was ever designed to work within a browser environment. 

However, it also looks like the `gdax-node` dependencies are unnecessarily locked down to very specific versions.
https://github.com/coinbase/gdax-node/blob/master/package.json#L24-L27

What version of `ws` package are you using when connecting directly?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
