### ISSUE TITLE
getting best bids/asks from orderBookSync

### ISSUE THREAD

**Issue by adityamertia** [coinbase/coinbase-pro-node#251]
Hi,
Is there a way to fetch latest/best bids and asks from websocket. I see the orderBookSync which returns >30k entries list for bids and asks. How to get the sorted list and get the latest/best values for bids and asks. Is there a ready way available in the orderBookSync method?
Also how often does this list get updated from websocket?
Want to know from the community best ways of dealing with this method.

**Comment by rmm5t** [comment]
> How to get the sorted list and get the latest/best values for bids and asks. 

If this is all you need, you can get the best bid and ask from the `ticker` channel on the Websocket.  Much easier.

>  Is there a ready way available in the orderBookSync method?

Yes, but you'll have to navigate the [Binary Tree API](https://github.com/vadimg/js_bintrees#methods) against the `_bids` or `_asks` of the specific orderbook:

```
ob.books['BTC-USD']._bids.max().price.toString(); // => '11498.76'
ob.books['BTC-USD']._asks.min().price.toString(); // => '11498.78'
```

> Also how often does this list get updated from websocket?

Immediately, in real-time, but so do the prices in the `ticker` channel.

**Comment by adityamertia** [comment]
ok so i need lets say best 10 values of bids and asks so i cannot use ticker channel. I will then have to store 30k entries into datastore/memory locally and run btree on it to find best 10 values? And since the orderbook is updated in realtime so the time taken to get/store the 30k values can be greater than the time it takes to fetch new data, hence there can be a chance that updates are missed.
Another option would be use inmemory database like redis to keep the orderbook state updated in realtime and run redis sorting on the data. But problem is the size of orderbook is large. Won't that be an issue?

**Comment by rmm5t** [comment]
> ok so i need lets say best 10 values of bids and asks so i cannot use ticker channel.

GitHub Issues are not a good place for _changing_ hypothetical questions geared around helping you code or debug your application. You might have better luck asking questions on [StackOverflow.com](https://stackoverflow.com/) or hiring someone on [CodeMentor.io](https://www.codementor.io/).

> I used the above snippet and it returns me the price. Is there a way i can get the size as well.

Did you try to inspect the object?  It contains a list of orders, of which you can sum each order's size.

> Also my requirement is to fetch top 10 such values. I guess this requires changing the orderbookSync function? How does the UI keep top 40 or so values for both(bids, asks)?

The `OrderbookSync` is a Level 3 order book. Is sounds like you only need a Level 2 order book. 

Try subscribing to [the `l2update` channel](https://docs.gdax.com/#the-code-classprettyprintlevel2code-channel) on the websocket instead. The Level 3 order book contains all the same underlying data (with more detail), but a Level 2 order book will make your life easier. You'll have to manage the order book list yourself against that channel, but I think it will better match your needs.

**Comment by npomfret** [comment]
I'm also looking for a _nice_ way to get just the top few items from the order book.  I half solved it with the code below, but it's doesn't work for bids because of the way the RBTree is sorted.  If you replace the asks with the bids you get the worst prices rather than the best.  

```
const orderbookSync = new GDAX.OrderbookSync(['BTC-USD', 'ETH-USD']);

function printTop(symbol, count) {
    const book = orderbookSync.books[symbol];

    let it = book._asks.iterator();
    let item;
    let i = 0;

    while ((item = it.next()) !== null) {
        i++;

        let quantity = 0;
        item.orders.forEach((order) => quantity += order.size.toNumber());

        console.log(i, {price: item.price.toString(), quantity: new BigNumber(quantity).toString()});

        if (i >= count)
            break
    }

    console.log();
}

setInterval(() => {
    printTop('BTC-USD', 5);
}, 5000);
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
