### ISSUE TITLE
Please document profile_id

### ISSUE THREAD

**Issue by Bomper** [coinbase/coinbase-pro-node#256]
https://docs.gdax.com/#accounts shows `profile_id` in the response example, but the field is not documented under `ACCOUNT FIELDS`.

Also, `holds` should be `hold`.

**Comment by fb55** [comment]
Thanks for the report! Would you mind opening a PR?

**Comment by rmm5t** [comment]
@fb55 Wouldn't this be a GDAX API documentation related issue (worthy of the `gdax-doc-requests` label)? Not something someone could submit a PR to fix?

**Comment by rmm5t** [comment]
@fb55 What's the process for improving the gdax docs? I just added the `gdax-doc-requests` tag here, but who should be tagged such that this gets tracked?

**Comment by a--hoang** [comment]
@rmm5t feel free to tag me

**Comment by AntonioJuliano** [comment]
Any progress on this?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
