### ISSUE TITLE
FULL orderbook - skipping messages

### ISSUE THREAD

**Issue by MaximG1234** [coinbase/coinbase-pro-node#280]
Hi all,

This is a duplication of the issue as described here: https://stackoverflow.com/questions/49228552/gdax-coinbase-api-full-orderbook-skipping-messages

But I figured it would be worth adding it to your existing issue log.
-------------------------------------------------------------------------

I'm using the GDAX API [Websocket Stream][1] to try and create a copy of the full orderbook. 

I've got a very simple implementation using WebSocketSharp and Im basically doing something like this.

```

    private readonly WebSocket _webSocket = new WebSocket("wss://ws-feed.gdax.com");
    
    _webSocket.OnMessage += WebSocket_OnMessage;
    _webSocket.Connect();
    _webSocket.Send(JsonConvert.SerializeObject(new BeginSubscriptionMessage()));
    
    private void WebSocket_OnMessage(object sender, MessageEventArgs e)
    {
        var message = JsonConvert.DeserializeObject<BaseMessage>(e.Data);
        switch (message.Type)
        {   
            case "match": //A trade occurred between two orders. 
                MatchMessage matchMessage = JsonConvert.DeserializeObject<MatchMessage>(e.Data);
                _receivedMatchQueue.Enqueue(matchMessage);
                break;
            case "received": //A valid order has been received and is now active. This message is emitted for every single valid order as soon as the matching engine receives it whether it fills immediately or not.
                ReceivedMessage receivedMessage = JsonConvert.DeserializeObject<ReceivedMessage>(e.Data);
                _receivedMessageQueue.Enqueue(receivedMessage);
                break;
            case "open": //The order is now open on the order book. This message will only be sent for orders which are not fully filled immediately. remaining_size will indicate how much of the order is unfilled and going on the book.
                OpenMessage openMessage = JsonConvert.DeserializeObject<OpenMessage>(e.Data);
                _receivedOpenQueue.Enqueue(openMessage);
                break;
            case "done": //The order is no longer on the order book. Sent for all orders for which there was a received message. This message can result from an order being canceled or filled. 
                DoneMessage doneMessage = JsonConvert.DeserializeObject<DoneMessage>(e.Data);
                _receivedDoneQueue.Enqueue(doneMessage);
                break;
            case "change": //Existing order has been changed
                ChangeMessage changeMessage = JsonConvert.DeserializeObject<ChangeMessage>(e.Data);
                _receivedChangeQueue.Enqueue(changeMessage);
                break;
            case "activate": //Stop order placed
                //Console.WriteLine("Stop Order Placed");
                //ActivateMessage activateMessage = JsonConvert.DeserializeObject<ActivateMessage>(e.Data);
    
                break;
            case "subscriptions":
                break;
            case "ticker":
                TickerMessage tickerMessage = JsonConvert.DeserializeObject<TickerMessage>(e.Data);
                _receivedTickerQueue.Enqueue(tickerMessage);
                break;
            case "l2update":
                        
                break;
        }
    }
```

The problem I am running into is that when I look at the sequence numbers as received through both the RECEIVED and OPEN messages I can see they are not sequential which ([based on the following information][2]) suggests that messages are being skipped.

Basically you end up with something like this 

    Open Message SequenceId: 5359746354
    Open Message SequenceId: 5359746358
    Open Message SequenceId: 5359746361
    Open Message SequenceId: 5359746363
    Open Message SequenceId: 5359746365
    Open Message SequenceId: 5359746370
    Open Message SequenceId: 5359746372

I have tried testing this on Azure, just to make sure that it wasn't a bandwidth limitation on my end and the results were largely similar.

So given this, how is it possible to build a complete 'real-time' orderbook using the 'full' websocket stream if messages are dropped? Can I just safely ignore them? Or do I just somehow clear orphaned values?

Any advice from anyone having done something similar would be extremely appreciated.

  [1]: https://docs.gdax.com/#the-code-classprettyprintfullcode-channel
  [2]: https://docs.gdax.com/#sequence-numbers

**Comment by LFoglietti** [comment]
I opened a similar issue under Gdax TT regarding the tickertape.

https://github.com/coinbase/gdax-tt/issues/175

I agree with you. In my opinion there are many message dropped. especially when the activity on the market become busy.

**Comment by JensKDK** [comment]
The sequence numbers/id's are per channel. In you switch statement, from "match" until "activate", are message in the full channel. They share the same sequence, meaning id 1 can be "open", 2 "close", 3 "change" etc.
The "subscriptions" message is a response to the "subscribe" command when establishing the connection. I'm not sure the sequence even matters here, or exists. It shouldn't matter, as there is only one response to one "subscribe" command.
The "ticker" message is from the ticker channel. It will have it's own sequence.
Same with "12update". It's a message from the level2 channel, and it will have it's own sequence.
You need to handle sequencing PER channel you subscribe to. The are NO message losses in either of the channels you are subscribing to, and if a sequence number is missing on a channel, you order book is likely out of sync, and you have to rebuild it. Yes, it's messy, but when it works, it works.
I have had this running for a long time, and have no problems. I know the streams work as they are supposed to. Hope this helped. Good luck.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
