### ISSUE TITLE
getProductTradeStream rate limit handling hijacked by thrown error

### ISSUE THREAD

**Issue by kenfehling** [coinbase/coinbase-pro-node#320]
The function `getProductTradeStream` [handles error code 429](https://github.com/coinbase/gdax-node/blob/bf347b1122f9b85ee835b2c8e2e90338dab81e0a/lib/clients/public.js#L209-L215) however in [this part](https://github.com/coinbase/gdax-node/blob/bf347b1122f9b85ee835b2c8e2e90338dab81e0a/lib/clients/public.js#L67-L69) an error is thrown for any response with a code > 299, so the `getProductTradeStream` function never gets to see it.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
