### ISSUE TITLE
cb-access-key is not allowed by Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by givanse** [coinbase/coinbase-pro-node#33]
I'm trying to use the library from the browser and I see this:

> Fetch API cannot load https://api.gdax.com/accounts. Request header field cb-access-key is not allowed by Access-Control-Allow-Headers in preflight response.

From this [forum thread](https://community.coinbase.com/t/coinbase-exchange-api-error/9696) it is suggested that what might be happening is that the message is not signed.

However the library [does it](https://github.com/coinbase/gdax-node/blob/63ed959b4b500ce5583931ef5a7a485d50fae06f/lib/clients/authenticated.js#L60).

```
var sig = signRequest(auth, method, relativeURI, opts);
```

The only way to solve for this is to have the backend add the headers to the preflight response. Is it something that could happen?

**Comment by dysect** [comment]
+1, same issue. Trying to access via node library.

**Comment by aastein** [comment]
+1

**Comment by aastein** [comment]
This should be closed. https://community.coinbase.com/t/help-request-header-field-cb-access-key-is-not-allowed-by-access-control-allow-headers/819

**Comment by jakowicz** [comment]
Link is broken !

**Comment by jerry-gdd** [comment]
Any word on this? Having the same issue

**Comment by beyond94** [comment]
I'm having the same issue. When launching my call to the "/accounts" endpoint (with the four required headers) using Postman however, it does work... When running the call from a browser (combo of jQuery and PHP for auth), I get the error **"Request header field CB-ACCESS-PASSPHRASE is not allowed by Access-Control-Allow-Headers in preflight response."**

Any word on how to fix this? I've tried using the additional headers:
- "Access-Control-Allow-Origin": "*",
- "Access-Control-Allow-Methods": "GET",
- "Access-Control-Allow-Headers": "*"

But adding these extra headers still doesn't fix the issue.

Any help will be much appreciated!

**Comment by JBaczuk** [comment]
This link suggests that it will not be allowed: https://developers.coinbase.com/docs/merchants/technical-faq#ajax

See "Why isn’t my AJAX request to the API working?" at the bottom

**Comment by sealocal** [comment]
Why not allow the headers for the preflight/client request? Is it a security or performance concern?  Otherwise, does CB simply want to limit activity to servers instead of a wide array of clients?

**Comment by JBaczuk** [comment]
I'm guessing it's the latter, but who knows.

**Comment by trevorhere** [comment]
Any updates on this issue?

**Comment by VZnode** [comment]
Hi, have same issue. 
Have nodejs code that fetch https://api.gdax.com/BCH-BTC/ticker  and it works, only User-Agent headers is set there, but then i try to load same link from chrome, firefox, or node-red getting error {"message":"CB-ACCESS-KEY header is required"}, very strange behavior, any clues ?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
