### ISSUE TITLE
cancel order response shows successful cancel even though the order got filled a second before

### ISSUE THREAD

**Issue by atbrennan** [coinbase/coinbase-pro-node#334]
I had a buy order sitting in litecoin, then it got filled, but before the response actually came down, cancelorder was called and the api response showed no errors or that it was already filled.
based on the time of each happening, there would have been less than a second in between.

is this something that has ever happened for anyone else?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
