### ISSUE TITLE
Coinbase Pro Candles Endpoint Unreliable

### ISSUE THREAD

**Issue by luyongxu** [coinbase/coinbase-pro-node#348]
I am looking to download historical data using the Coinbase Pro's REST API candles endpoint:

GET /products/<product-id>/candles)

I have found that the response from this endpoint is unreliable. Sometimes the response contains data and sometimes the response does not contain data.

Steps to reproduce:

1. Copy the following endpoint:

https://api.pro.coinbase.com/products/BTC-USD/candles?start=2014-07-20T00%3A00%3A00.0Z&end=2015-02-05T00%3A00%3A00.0Z&granularity=86400

2. Open in browser of choice

3. Refresh several times

4. Observe that roughly 20 percent of the time, the response contains no data.

Can anyone explain what is happening?

**Comment by nomuppets** [comment]
I have experience the same problem. I suspect it's some sort of weird caching problem on the gdax's end.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
