### ISSUE TITLE
TypeError: authedClient.depositPayment is not a function

### ISSUE THREAD

**Issue by auicheng** [coinbase/coinbase-pro-node#350]
I called the the depositPayment method as the way in the docs. 
`const depositPaymentParamsUSD = {
  amount: '100.00',
  currency: 'USD',
  payment_method_id: 'bc6d7162-d984-5ffa-963c-a493b1c1370b', // ach_bank_account
};
authedClient.depositPayment(depositPaymentParamsUSD, callback);`
How to solve this?

**Comment by vansergen** [comment]
It is solved on the latest `master` branch.

**Comment by fb55** [comment]
Thanks @vansergen!
