### ISSUE TITLE
unable to get CB-ACCESS-KEY 

### ISSUE THREAD

**Issue by grvlthr** [coinbase/coinbase-pro-node#354]

**Comment by fb55** [comment]
API keys are generated in the settings for Coinbase Pro.

**Comment by grvlthr** [comment]
CB-ACCESS-KEY  and API key both are same ?

**Comment by fb55** [comment]
https://github.com/coinbase/coinbase-pro-node#the-authenticated-api-client shows how you can instantiate a private client instance with the API keys.

**Comment by grvlthr** [comment]
thanks
