### ISSUE TITLE
API Rate Limiting

### ISSUE THREAD

**Issue by nikulis** [coinbase/coinbase-pro-node#61]
(Inspired by @awitherow's [question](https://github.com/coinbase/gdax-node/pull/60#discussion_r121255275))

Right now it seems that the only method that has any notion of API rate limiting is `PublicClient.fetchTrades`.

I think it would be a good idea to somehow abstract rate limiting lower down closer to the actual http/request calls so that all of the clients' methods can use it transparently.

Looking at [docs.gdax.com/#rate-limits](https://docs.gdax.com/#rate-limits), it says that

> When a rate limit is exceeded, a status of 429 Too Many Requests will be returned.
> ### REST API
> **PUBLIC ENDPOINTS**
> We throttle public endpoints by IP: 3 requests per second, up to 6 requests per second in bursts.
> **ENDPOINTS**
> We throttle private endpoints by user ID: 5 requests per second, up to 10 requests per second in bursts.

Knowing these limits, and with a single internal handler of rate limiting, we could theoretically keep track of the requests going out and preemptively hold them (maybe even in a queue) if it would be expected to return a `429` anyways. That way, we wouldn't have to wait an entire RTT to find out that we hit a limit, potentially having tried to fire off more in the meantime.

Sidenote: I'm not sure what GDAX defines as "bursts", I haven't found anything about it elsewhere in the docs.

**Comment by awitherow** [comment]
And execute the requests one by one via a promise interface?

**Comment by nikulis** [comment]
Having a queue that synchronously executes one after the other would probably be the easiest thing to implement, and might be a good place to start.

We may also consider a scenario where, if the API is limited to `n` requests per second, a client that has been idle for a while wants to send `n` new, independent requests very quickly. Theoretically, the client should be able to send all of those at once without having to wait for a response from each one. To support that in combination with preemptive limiting, we would some more internal state that remembers timing.

My initial thought is that a `{Public,Authenticated}Client` instance will need to remember the timestamp of the last `n` requests that successfully fulfilled. The timing information, coupled with the request queue, would determine whether a request could be fired now, fired after some time from now, or added to the end of the queue to be handled later after other pending requests.

And for completeness' sake, it will still need to handle catching `429` responses and then re-enqueuing / retrying requests.

**Comment by nikulis** [comment]
With the switch to using `superagent` for network requests, there's a plugin [`superagent-throttle`](https://github.com/leviwheatcroft/superagent-throttle) that adds the ability to automatically handle a lot of this logic.

The implementation in #86 uses this throttling by default.

**Comment by nikulis** [comment]
In the process of taking a new pass at implementing rate limiting, I've come up with a few questions.

**1. Does anyone have more specific information on GDAX' rate limiting behavior?**

The GDAX docs say:

> **Public Endpoints**
> We throttle public endpoints by IP: 3 requests per second, up to 6 requests per second in bursts.
> 
> **Private Endpoints**
> We throttle private endpoints by user ID: 5 requests per second, up to 10 requests per second in bursts.

I'm not sure what "in bursts" quite means, or if there's any way we could reliably anticipate being able to successfully fire bursts client-side.

Also, is the distinction between public/private endpoints per URL, or by whether valid auth credentials are included? E.g., what if an AuthenticatedClient instance were used to call a public endpoint?

**2. Configurability of throttling**

I currently have `rateLimit` as an accepted property on client constructor options, e.g.

```js
const publicClient = new Gdax.PublicClient(apiURI, { rateLimit: 4 });
```

where the client will throttle requests to 4 per second. By default, throttling uses GDAX' advertised rate limits. It can be disabled by passing a falsy value (`rateLimit: false`).

**(2a)** Should throttling be on by default?

I have also worked on automatically pausing + retrying requests when a `429` response is received (there may be subtle differences in how a client-side throttle times things vs. how GDAX measures for their own rate limiting).

**(2b)** Should auto-429 retrying be on by default? Right now I'm thinking that it's on if throttling is on, e.g. if you opt out of throttling (`rateLimit: false`), then you get to handle 429s on your own.

**(2c)** Should throttling be handled "globally" (e.g. use some singleton queue), or per client instance? I'm leaning towards per client instance, since users technically only need one client (as Auth extends Public).

**3. Can the `request` library be replaced? (What should the response object format be, for both success and error states? (maybe another issue))**

There are a few notable cross-platform request libraries, including [request](https://www.npmjs.com/package/request), [superagent](https://www.npmjs.com/package/superagent), and [axios](https://www.npmjs.com/package/axios), each of which has its own pros and cons for this project.

request is what's currently used, and because its own `response` objects are currently returned to users of the callback API, changing it may be backward-incompatible unless we can map other libraries' response formats. Tests account for only a select few fields in the returned responses, though it is feasible that users may be depending on others. (see [this comment](https://github.com/coinbase/gdax-node/pull/86#issuecomment-355633592))

axios and superagent both have the benefits of exposing a promise API by default as well as being configurable. Superagent has an existing community plugin for throttling requests to a given rate limit ([superagent-throttle](https://www.npmjs.com/package/superagent-throttle)). On the other hand, subjectively, superagent's API feels less polished and I do not fully trust its [docs](https://visionmedia.github.io/superagent/), and I have had a harder time debugging with it than axios.

**Comment by fb55** [comment]
__(1)__ We allow users to go over the limit for a short time. Iirc we are purposefully vague here, as that timeframe can be reduced eg. when we see a lot of traffic. 

I'd say in combination with 429 retrying the upper limits should be allowed per timeframe, with the lower one as the allowed number of concurrent requests. 

__(2a)__ Definitely. 429s aren't the best user experience, having some mechanism that already throttles before that (even if it permits more requests than the backend will allow) should be great.

__(2b)__ `rateLimit: false` as a switch for the user to take full control seems reasonable. Otherwise having it as an additional mechanism to handle cases like in (1) seems great.

__(2c)__ Given that we have public and authenticated rate limits having them per instance is probably best.

__(3)__ I'm a big fan of @rmm5t's proposal. Let's wrap the request, so we're independent of request libraries in the future.

superagent has a pretty big ecosystem advantage. For now I'd opt for it (especially for the rate limiter), but definitely something we can revisit later.

**Comment by blair** [comment]
Hi @fb55 ,

Regarding question 1 above: "Also, is the distinction between public/private endpoints per URL, or by whether valid auth credentials are included? E.g., what if an AuthenticatedClient instance were used to call a public endpoint?"

BTW, the `limiter` module does rate limiting and allows for bursting. It is used in the `gdax-tt` module.

**Comment by fb55** [comment]
> Also, is the distinction between public/private endpoints per URL, or by whether valid auth credentials are included? E.g., what if an AuthenticatedClient instance were used to call a public endpoint?

The latter. If you provide credentials your limits are bumped for public endpoints.

> BTW, the limiter module does rate limiting and allows for bursting. It is used in the gdax-tt module.

Good to know :)

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
