### ISSUE TITLE
OrderbookSync returns stale data

### ISSUE THREAD

**Issue by petercerno** [coinbase/coinbase-pro-node#80]
Hi, when creating `OrderbookSync` as follows:

```
this._orderbookSync = new Gdax.OrderbookSync(
      productIds, apiURI, websocketURI, this._authClient);
```

And then reading the `bid` / `ask` prices as follows:

```
let state = this._orderbookSync.books[productId].state();
let bid = state.bids[0].price;
let ask = state.asks[0].price;
```

What happens is that `bid` or `ask` prices stop being updated (after some time) and become stale (inconsistent with what I see on https://www.gdax.com/trade/). This happens randomly, but often enough, that I have to re-create `OrderbookSync` almost every minute. Is there a bug? (It used to work fine before).

I have used `ETH-EUR` product.

**Comment by pranksterN1** [comment]
PR #81 did't fix this issue  :(

**Comment by pranksterN1** [comment]
There is warning [here](https://docs.gdax.com/#real-time-order-book):
> All open and match messages will always result in a change to the order book. Not all **done** or **change** messages will result in changing the order book. These messages will be sent for received orders which are not yet on the order book. **Do not alter the order book for such messages**, otherwise your order book will be incorrect.

But [here](https://github.com/coinbase/gdax-node/blob/8611f3628eef1d6d2e9e83d1b7218a359854c428/lib/orderbook_sync.js#L113) I can see that "done" and "change" messages are processed in orderbook. Is this correct ?

**Comment by gmelika** [comment]
I think this comment might explain the stale data issue:

https://github.com/coinbase/gdax-node/issues/104#issuecomment-327882166

**Comment by fb55** [comment]
This library refetches orders when it reconnects. Not sure what the exact origin of this is, especially as this seems limited on one side of the book. I hope to update gdax-node to use our level 2 channel soon, which should fix this issue. (See #82.)

**Comment by ztnark** [comment]
I am seeing this issue in 0.6.0. Is there a solution, or is OrderBookSync unusable? Thank you.

**Comment by johanhenriksson** [comment]
Im seeing this problem in 0.8.0 as well. Asks stop updating after a while, bids keep updating as normal. Are there any known workarounds?

**Comment by BGrades** [comment]
I am seeing the same problem in 0.8.0. I have the sync orderbook created with 4 productIds. And as @johanhenriksson described the asks stops updating after some time. Worth pointing out that the asks are stoping to update one by one. Does anyone know the reason for that or have a workaround? Thank you.

**Comment by BGrades** [comment]
Okay, I think @tensleep, who raised issue #308 "Order book resync (after dropped message) appears broken" pointed out the issue correctly. I changed the code to clear the bids and asks on resync and haven't seen the issue for the past week. There are several issues opened regarding the OrderbookSync and my guess is that most of them are related to the problem pointed out by tensleep. Hope it helps others in resolving the bug.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
