### ISSUE TITLE
Proposal: Switch to level 2 book

### ISSUE THREAD

**Issue by fb55** [coinbase/coinbase-pro-node#82]
We recently switched the website (https://www.gdax.com) to a level 2 book (only price levels, no specific orders). This vastly reduced the bandwidth requirements for clients and allows us to send the entire book when initially subscribing. It also means clients do not need to take care of potentially dropped messages on the full feed.

The goal of this issue is to get some feedback on whether this switch would be an option for this library as well. Most trading bots probably aren't interested in the exact orders — perhaps to get an idea of the execution order (as this is FIFO), but even that should be rare.

Please leave a comment if you have any concerns!

**Comment by pranksterN1** [comment]
In my mind, ability to choose level (1-3) of sync order book would be the great feature.

**Comment by fb55** [comment]
@pranksterN1 Level 3 books are way more complex than level 2 books. While I agree that this would be generally a nice feature, the goal of this to both improve the performance and reduce the complexity of this library.

Level 1 might be a nice future addition, but as the level 2 book already contains that information having that probably suffices.

**Comment by b-zee** [comment]
Is this about the Orderbook Sync (Websocket feed)? If yes:

According to the API documentation, level 2 only returns the top 50 bids and asks. How is the client supposed to keep the full order book in sync, without knowing the state of the remaining bids and asks?

As far as I can tell from the docs, level 2 cannot be configured for the Websocket feed. (However, https://www.gdax.com does seem to provide a `channels` parameter though it is undocumented so I deem it unfit.)

It'd be great to use level 2, instead of level 3 to keep a synchronized full order book, but with the current API I'm unsure how.

**Comment by fb55** [comment]
The website already retrieves full level 2 snapshots via the feed. We are currently finishing up the flow for subscribing to channels, as soon as that's done the docs will be updated accordingly.

**Comment by pranksterN1** [comment]
@fb55,
Do you have an approximate date for completing that work ?

**Comment by fb55** [comment]
@pranksterN1 No exact date, but it shouldn't be much later than the first week of September.

**Comment by fb55** [comment]
We finally rolled this out yesterday. Docs are live at https://docs.gdax.com/#websocket-feed — this hasn't been officially announced yet (we will do so next week), but for now feel free to experiment with it.

The [trading toolkit](https://github.com/coinbase/gdax-tt) we published this week already uses the new channels and I'd like to switch this library to something similar.

**Comment by pranksterN1** [comment]
@fb55, Thank you for your answers. 
I faced with the problem with new ws feed API.
Could you clarify why the first message I received doesn't have side, time, trade_id, last_size fields?
Or should  I skip all messages until "subscriptions" message will be received.
<details><summary>ws messages  [click here to expand]</summary>
<p>
request:

```javascript
{  
   "type":"subscribe",
   "product_ids":[  
      "BTC-USD"
   ],
   "channels":[  
      "ticker"
   ]
}
```
received data:

```javascript
{  
   "type":"ticker",
   "sequence":4077559280,
   "product_id":"BTC-USD",
   "price":"3595.00000000",
   "open_24h":"3869.02000000",
   "volume_24h":"16938.74579088",
   "low_24h":"3595.00000000",
   "high_24h":"3875.54000000",
   "volume_30d":"470252.79261935",
   "best_bid":"3592.84",
   "best_ask":"3595.04"
}
```

```javascript
{  
   "type":"subscriptions",
   "channels":[  
      {  
         "name":"ticker",
         "product_ids":[  
            "BTC-USD"
         ]
      }
   ]
}
```

```javascript
{  
   "type":"ticker",
   "sequence":4077560540,
   "product_id":"BTC-USD",
   "price":"3598.65000000",
   "open_24h":"3869.02000000",
   "volume_24h":"16938.74579365",
   "low_24h":"3598.65000000",
   "high_24h":"3875.54000000",
   "volume_30d":"470252.79262212",
   "best_bid":"3592.9",
   "best_ask":"3598.65",
   "side":"buy",
   "time":"2017-09-22T13:29:42.602000Z",
   "trade_id":21221450,
   "last_size":"0.00000277"
}
```

</p></details>

**Comment by fb55** [comment]
The first message is intended to give you an instant impression of the current market conditions, analogous to the snapshot message you get when you subscribe to the level 2 channel. Definitely something we need to document.

**Comment by Arombalski** [comment]
Was this ever rolled out?  I see in the orderbookSync lib that there is a "bookLevel = 3" argument but changing it to level 2 results in assertion errors.

**Comment by rmm5t** [comment]
> Was this ever rolled out? I see in the orderbook_sync lib that there is a "bookLevel = 3" argument but changing it to level 2 results in assertion errors.

@Arombalski The main GDAX Websocket API added level 2 support to the websocket feed, but no, this has not been implemented in gdax-node yet. `OrderbookSync` still relies on level 3.

**Comment by adityamertia** [comment]
Hi,
I am using orderbookSync of gdax-node and I am facing same issue where orderbook data randomly becomes stale. Is there a way yet in gdax-node to fetch correct data (may be using level2)? Or if i can use any other way of keeping my orderbook updated? Does gdax trading toolkit help with keeping orderbook in sync?

**Comment by adityamertia** [comment]
Hello,
Is this done yet or planned for anytime soon?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
