### ISSUE TITLE
Direct crypto deposit via address

### ISSUE THREAD

**Issue by passabilities** [coinbase/coinbase-pro-node#91]
I know that this is possible as [this support page](https://support.gdax.com/customer/en/portal/articles/2430150-how-to-deposit-and-withdraw-digital-currencies) describes where to go on the exchange to get the deposit address. 

However after surfing through the API docs, this does not seem to be an implemented endpoint.

**Comment by peterhanneman** [comment]
+1 Fetching and perhaps even generating deposit addresses would be quite helpful.

**Comment by fb55** [comment]
Fixed in #90

**Comment by passabilities** [comment]
@fb55 I was thinking more in terms of fetching an address from GDAX to deposit to not withdraw.

**Comment by passabilities** [comment]
You see what I'm saying? Cause I know that you can do it cause I've done it on the GDAX platform but it doesn't appear that the API endpoint has been created.

**Comment by fb55** [comment]
Right — I'm a bit surprised that we haven't documented that endpoint. Let me get back to you about that.

**Comment by passabilities** [comment]
@fb55 any updates?

**Comment by LRonHubs** [comment]
The transactoin hash needs to be included too for deposits and withdrawals

**Comment by tomekit** [comment]
@fb55 
Any updates on this?

BTW. What are the other ways to deposit crypto on GDAX via API? Can I reuse the old already generated manually address?

**Comment by bahmanh** [comment]
@tomekit We can reuse an old address.
"All addresses that have been generated for your account will remain associated with your account forever. They are safe to re-use to receive future payments, but for the prior stated reasons, we recommend using a unique address for all transactions."
https://support.coinbase.com/customer/portal/articles/2276500

**Comment by pcfreak30** [comment]
Was able to figure it out.

```gdax_authed.post(['coinbase-accounts','ACCOUNT ID','addresses']).then((address)=>{
.....
})```

Use the ID from getAccounts()

**Comment by sagivo** [comment]
@pcfreak30 thanks for this undocumented hack. i made a small script to print all the addresses: 
```js
const data = await gdax_authed.getCoinbaseAccounts();
const accounts = data.filter(account => account.type !== 'fiat').map(account => ({ id: account.id, currency: account.currency }));
const res = {};
for (const account of accounts) {
  res[account.currency] = (await this.privateApi.post(['coinbase-accounts', account.id, 'addresses'])).address;
}
console.log(res);
```
hope it help you guys.

**Comment by pcfreak30** [comment]
@sagivo when i tried similar got a 404. so i went to dev tools network to get the account id being requesting from the api as a normal user and just added as a constant in code. Just have to go and generate a new deposit address to get it.

**Comment by awasunyin** [comment]
@sagivo I've checked the response of `/coinbase-accounts` but it does not include the addresses, only account ids, do you know if they made any changes? I also would like to log the list of actual deposit addresses

**Comment by passabilities** [comment]
@awasunyin There does not appear to be any changes on Coinbase's end at this time. @pcfreak30 and @sagivo posted a hack above for the time being.

**Comment by passabilities** [comment]
I will work on integrating the hack to the package.

**Comment by flxfxp** [comment]
Unfortunately it doesn't seem to be working anymore, returns a 404 not found- are you experiencing the same thing?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
